const express = require("express")
const router = express.Router()
const controller = require("../controllers/theatreController")
const {verifyJWt} = require("../middlewares/authenticationMiddleware")
const {checkAdmin} = require("../middlewares/roleMiddleware")

router.post('/theatre/add', verifyJWt, checkAdmin, controller.addtheatreFunction)
router.delete('/theatre/remove/:id', verifyJWt, checkAdmin, controller.removetheatreFunction)
router.patch('/theatre/update/:id', verifyJWt, checkAdmin, controller.updatetheatreFunction)
router.get('/theatre/all-theatre',controller.getAllTheatres)
router.get('/theatre/get-theatre/:id',controller.getTheatreById)
router.get('/theatre/theatre-by-city',controller.getTheatreByCity)
router.get('/theatre/get-theatre-shows/:id',controller.getTheatreShows)
router.get('/theatre/get-pending', verifyJWt, checkAdmin, controller.getPendingTheatres)
router.patch('/theatre/approve/:id', verifyJWt, checkAdmin, controller.approveTheatre)
module.exports = router